import { createApp } from 'vue'
import { createPinia } from 'pinia'
import App from './App.vue'
import router from './router'
import './styles/tokens.css'
import './styles/base.css'
import './styles/tree.css'
import './styles/dirpicker.css'
import './styles/dashboard.css'
import './styles/detail.css'
import './styles/report.css'
import './styles/evidence.css'
import './styles/sft.css'
import './styles/expert.css'

createApp(App).use(createPinia()).use(router).mount('#app')
